### ISSUE TITLE
Ausência do Header Location na Criação de Novos Recursos

### ISSUE THREAD

**Issue by jonathanmdr** [ocrisurbainski/spring-webflux-sample#3]
https://github.com/ocrisurbainski/spring-webflux-sample/blob/b9890549d60132fe71702fd02cfec6c6f42c670e/src/main/java/br/com/urbainski/springwebfluxsample/people/infra/controller/PeopleController.java#L29-L35

 - Normalmente os métodos de criação ao serem invocados devolvem na resposta um Header de nome `Location` que contém o endereço URI para realizar a busca no recurso recém criado.
 
 _Sugeriria utilizar o `ResponseEntity` para montar a resposta adicionando o Header `Location`_

**Comment by ocrisurbainski** [comment]
Neste caso o header `Location` deve ser adicionado para o `insert` e `update`?

**Comment by jonathanmdr** [comment]
Somente no caso do `insert`, que é o cenário onde o recurso ainda não existe, e após ser criado nós conseguimos recuperar a informação sobre ele através deste Header.

No caso do `update` nós já sabemos qual é o recurso que estamos manipulando, por isso não faz sentido adicionar o Header.
