### ISSUE TITLE
Classe Inutilizada

### ISSUE THREAD

**Issue by jonathanmdr** [ocrisurbainski/spring-webflux-sample#7]
https://github.com/ocrisurbainski/spring-webflux-sample/blob/b9890549d60132fe71702fd02cfec6c6f42c670e/src/main/java/br/com/urbainski/springwebfluxsample/people/PeopleFacade.java#L12

 - Essa Facade parece não estar sendo utilizada em nenhum lugar do projeto, se for o caso, poderia remover, ou se ela deveria ser utilizada, verificar o que está sendo injetado nas camadas externas.

**Comment by ocrisurbainski** [comment]
Está classe é a implementação da interface `PeopleOperations`, ela não é utilizada diretamente no sistema, a interface `PeopleOperations` é injetado no controller de pessoas, e consequentemente é uma instância de `PeopleFacade` é injetada neste ponto.

Basicamente este é o service.

A motivação de usar assim seria aplicar o design pattern Facade:

"O Facade é um padrão de projeto estrutural que fornece uma interface simplificada para uma biblioteca, um framework, ou qualquer conjunto complexo de classes."

https://refactoring.guru/pt-br/design-patterns/facade

Entre os modos utilizados na empresa, foi o que me pareceu o melhor.

**Comment by jonathanmdr** [comment]
Ótimo ponto, não havia me atentado à isso, mas está totalmente correto a forma como utilizou!
